survey/singlepageapp/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


urlpatterns = [
    url(r'^surveyentry/new/$', views.survey_entry_new, name='survey_entry_new'),
    path('ajax/load-regions/', views.load_region, name='ajax_load_regions'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
    url(r'^surveyentry/map/$', views.display_map, name='display_map'),
    url(r'^surveyentry/majors/$', views.display_pie_plot, name='display_map'),

]

survey/survey/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('singlepageapp.urls')),

]

survey/singlepageapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
#from django_countries.fields import CountryField
from cities_light.models import Country, City, Region
from django.contrib import admin

class SurveyResponse(models.Model):

    ENGINEERING_MAJORS = ['Ingeniería Aeronáutica', 'Ingeniería Ambiental', 'Ingeniería Biomédica', 'Ingeniería Civil',
                          'Ingeniería Electromecánica', 'Ingeniería Electrónica', 'Ingeniería Industrial',
                          'Ingeniería Mecánica', 'Ingeniería Química',
                          'Ingeniería en Agrimensura', 'Ingeniería en Computación']
    ENGINEERING_MAJORS_CHOICES = [(f'{id}', major) for id, major in enumerate(ENGINEERING_MAJORS)]



    #on_delete cascade -> if a user is deleted then the agent linked to that user will be erased also
    #user has username,password,email,firstname and lastname attributes. That ones must not be redefined at Agente.
    mail = models.EmailField(unique=True, verbose_name='Correo Electronico')
    nombre = models.CharField(max_length=100, null=False, default='', verbose_name='Nombre')
    apellido = models.CharField(max_length=100, null=False, default='', verbose_name='Apellido')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, verbose_name='País')
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, verbose_name='Provincia/Region')
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, verbose_name='Ciudad')
    remoto = models.CharField(choices=[('1', 'Si'), ('0', 'No')], verbose_name='remoto', null=False, max_length=1)
    major = models.CharField(choices=ENGINEERING_MAJORS_CHOICES, verbose_name='Carrera', null=False, max_length=2)
    question_expectancy_text_field = models.TextField(max_length=1500, blank=False, verbose_name='expectancy')
    created_at = models.DateTimeField(auto_now_add=True)


#admin.site.register(SurveyResponse)

survey/singlepageapp/forms.py
from django import forms
from .models import SurveyResponse
from cities_light.models import Country, City, Region

EMPTY = "--------"

class SurveyResponseForm(forms.ModelForm):
    class Meta:
        model = SurveyResponse
        #fields = ('nombre', 'apellido', 'cuit', 'localidad', 'calle', 'numero', 'telefono', 'mail', 'descripcion')
        exclude = ()
        labels = {'country': 'País (Desde dónde cursaran la materia)',
                  'region':'Provincia/Region (Desde dónde cursará la materia)',
                  'city':'Ciudad (Desde dónde cursará la materia)',
                  'remoto':'¿El lugar desde dónde cursará la materia coincide con su lugar de origen?',
                  'question_expectancy_text_field':'¿Que espera aprender en el curso?'}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['region'].queryset = City.objects.none()
        self.fields['city'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['region'].queryset = Region.objects.filter(country_id=country_id).order_by('name')
                if 'region' in self.data:
                    region_id = int(self.data.get('region'))
                    self.fields['city'].queryset = City.objects.filter(region_id=region_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['region'].queryset = self.instance.country.region_set.order_by('name')
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

survey/singlepageapp/views.py
from django.shortcuts import render
from .forms import SurveyResponseForm
from cities_light.models import Country, City, Region
from .plot import update_students_location_map, update_students_major_graph
# Create your views here.

def survey_entry_new(request):
    if request.method == "POST":
        form = SurveyResponseForm(request.POST)
        #form.cleaned_data['city'] = City.objects.get(pk=int(form.data['city']))
        if form.is_valid():
            survey_entry = form.save(commit=True)
            print("Survey Saved")
            return render(request, 'singlepageapp/survey_completed.html')
    else:
        form = SurveyResponseForm()
    return render(request, 'singlepageapp/survey_entry.html', {'form': form})


def load_region(request):
    country_id = request.GET.get('country')
    regions = Region.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'singlepageapp/region_dropdown_list_options.html', {'regions': regions})

def load_cities(request):
    #country_id = request.GET.get('country')
    region_id = request.GET.get('region')
    cities = City.objects.filter(region_id=region_id).order_by('name')
    return render(request, 'singlepageapp/city_dropdown_list_options.html', {'cities': cities})

def display_map(request):
    #update_students_location_map()
    return render(request, 'singlepageapp/map_template.html')

def display_pie_plot(request):
    update_students_major_graph()
    return render(request, 'singlepageapp/pie_plot_template.html')

survey/singlepageapp/templates/singlepageapp/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

survey/singlepageapp/templates/singlepageapp/map_template.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Lato", sans-serif
    }

    .w3-bar, h1, button {
        font-family: "Montserrat", sans-serif
    }

    .fa-anchor, .fa-coffee {
        font-size: 200px
    }
</style>

<!-- Header -->
<header class="w3-container w3-teal w3-center" style="padding:128px 16px;" >
    <h1 class="w3-margin w3-jumbo">Informática</h1>
    <h2 class="w3-xlarge">Comisión 5.1</h2>
</header>

    <body>
        <!-- First Grid -->
        <div class="w3-row-padding w3-padding-64 w3-container">
            <div class="w3-content w3-center " >
                 <img src="{% static 'singlepageapp/map-with-points.png' %}" style="max-height:766px; max-width:400px;">
            </div>
        </div>
    </body>

    <!-- Footer -->
    <!--
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
        <div class="w3-xlarge w3-padding-32">
            <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
    </footer>
    -->
</html>

survey/singlepageapp/templates/singlepageapp/pie_plot_template.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Lato", sans-serif
    }

    .w3-bar, h1, button {
        font-family: "Montserrat", sans-serif
    }

    .fa-anchor, .fa-coffee {
        font-size: 200px
    }
</style>

<!-- Header -->
<header class="w3-container w3-teal w3-center" style="padding:128px 16px;" >
    <h1 class="w3-margin w3-jumbo">Informática</h1>
    <h2 class="w3-xlarge">Comisión 5.1</h2>
</header>

    <body>
        <!-- First Grid -->
        <div class="w3-row-padding w3-padding-64 w3-container">
            <div class="w3-content w3-center" >
                 <img src="{% static 'singlepageapp/pie_plot.png' %}" style="max-height:994px; max-width:1380px;">
            </div>
        </div>
    </body>

    <!-- Footer -->
    <!--
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
        <div class="w3-xlarge w3-padding-32">
            <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
    </footer>
    -->
</html>

survey/singlepageapp/templates/singlepageapp/region_dropdown_list_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.pk }}">{{ region.name }}</option>
{% endfor %}

survey/singlepageapp/templates/singlepageapp/survey_completed.html
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="es">
<title>Encuesta</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Lato", sans-serif
    }

    .w3-bar, h1, button {
        font-family: "Montserrat", sans-serif
    }

    .fa-anchor, .fa-coffee {
        font-size: 200px
    }
</style>

<!-- Header -->
<!-- Header -->
<header class="w3-container w3-teal w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-xxxlarge">Informática</h1>
  <p class="w3-xxlarge">Comisión 5.1</p>
</header>
    <body>
        <!-- First Grid -->
        <div class="w3-row-padding w3-padding-64 w3-container">
            <div class="w3-content w3-center">
                <h1>Su respuesta ha sido registrada.</h1>
                <h1>Muchas Gracias</h1>
            </div>
        </div>
    </body>

    <!-- Footer -->
    <!--
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
        <div class="w3-xlarge w3-padding-32">
            <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
    </footer>
    -->
</html>

survey/singlepageapp/templates/singlepageapp/survey_entry.html
{% load widget_tweaks %}
{% load static %}
<!DOCTYPE html>
<html lang="es">
<title>Encuesta</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1, h2, h3, h4, h5, h6 {
        font-family: "Lato", sans-serif
    }

    .w3-bar, h1, button {
        font-family: "Montserrat", sans-serif
    }

    .fa-anchor, .fa-coffee {
        font-size: 200px
    }
</style>

<!-- Header -->
<header class="w3-container w3-teal w3-center" style="padding:128px 16px">
  <h1 class="w3-margin w3-xxxlarge">Informática</h1>
  <p class="w3-xxlarge">Comisión 5.1</p>
</header>


<body>
    <!-- First Grid -->
    <div class="w3-row-padding w3-padding-64 w3-container">
        <div class="w3-content">
            <div>
                <form method="post" id="personForm" data-regions-url="{% url 'ajax_load_regions' %}"
                      data-cities-url="{% url 'ajax_load_cities' %}">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form.visible_fields %}
                        <div class="form-group  form-row" id={{"id_row_"|add:field.html_name }}>
                            <label class="control-label col-sm-2">{{ field.label_tag }}
                                {% if field.field.required%}
                                <span class="required">(*)</span>
                                {% endif %}
                            </label>
                            <div class="col-sm-6" >
                                {% render_field field class+="form-control" style+="width:100%"%}
                                {{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    <div class="submit-row">
                        <input style="margin:0 0 0 8px;float:right" type="submit" value="Guardar" class="btn btn-primary"
                               name="_save">
                    </div>
                </form>
                        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                <script>
                    $("#id_country").change(function () {
                        var url = $("#personForm").attr("data-regions-url");  // get the url of the `load_cities` view
                        var countryId = $(this).val();  // get the selected country ID from the HTML input

                        $.ajax({                       // initialize an AJAX request
                            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                            data: {
                                'country': countryId       // add the country id to the GET parameters
                            },
                            success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_region").html(data);  // replace the contents of the city input with the data that came from the server

                            }
                        });

                    });

                    $("#id_region").change(function () {
                        var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
                        var regionId = $(this).val();  // get the selected country ID from the HTML input

                        $.ajax({                       // initialize an AJAX request
                            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                            data: {
                                'region': regionId       // add the country id to the GET parameters
                            },
                            success: function (data) {   // `data` is the return of the `load_cities` view function
                                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                            }
                        });

                    });
                </script>
            </div>
        </div>
    </div>
</body>

    <!-- Footer -->
    <!--
    <footer class="w3-container w3-padding-64 w3-center w3-opacity">
        <div class="w3-xlarge w3-padding-32">
            <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
    </footer>
    -->

</html>